"""Add detail field

Revision ID: 7598351f7cc8
Revises: 
Create Date: 2024-12-31 16:45:07.205836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7598351f7cc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detail', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price', schema=None) as batch_op:
        batch_op.drop_column('detail')

    # ### end Alembic commands ###
